import Menu from "./components/Menu";
import Rodape from "./components/Rodape";
import styles from "./components/rodape.module.css"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={styles.rodape}>
        <Menu/>
        {children}
        </body>
        <Rodape/>
    </html>
  )
}
